# Generated by Django 2.0.10 on 2019-02-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='talents',
        ),
    ]
