# Generated by Django 2.0.10 on 2019-02-05 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190204_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='college',
            new_name='author',
        ),
    ]
